var annotated_dup =
[
    [ "FAQChatBot", "namespace_f_a_q_chat_bot.html", [
      [ "Migrations", "namespace_f_a_q_chat_bot_1_1_migrations.html", [
        [ "Inicial", "class_f_a_q_chat_bot_1_1_migrations_1_1_inicial.html", "class_f_a_q_chat_bot_1_1_migrations_1_1_inicial" ],
        [ "AppDbContextModelSnapshot", "class_f_a_q_chat_bot_1_1_migrations_1_1_app_db_context_model_snapshot.html", "class_f_a_q_chat_bot_1_1_migrations_1_1_app_db_context_model_snapshot" ]
      ] ],
      [ "Models", "namespace_f_a_q_chat_bot_1_1_models.html", [
        [ "Aluno", "class_f_a_q_chat_bot_1_1_models_1_1_aluno.html", "class_f_a_q_chat_bot_1_1_models_1_1_aluno" ],
        [ "AppDbContext", "class_f_a_q_chat_bot_1_1_models_1_1_app_db_context.html", "class_f_a_q_chat_bot_1_1_models_1_1_app_db_context" ],
        [ "Categoria", "class_f_a_q_chat_bot_1_1_models_1_1_categoria.html", "class_f_a_q_chat_bot_1_1_models_1_1_categoria" ],
        [ "ChatBot", "class_f_a_q_chat_bot_1_1_models_1_1_chat_bot.html", "class_f_a_q_chat_bot_1_1_models_1_1_chat_bot" ],
        [ "Conversa", "class_f_a_q_chat_bot_1_1_models_1_1_conversa.html", "class_f_a_q_chat_bot_1_1_models_1_1_conversa" ],
        [ "ErrorViewModel", "class_f_a_q_chat_bot_1_1_models_1_1_error_view_model.html", "class_f_a_q_chat_bot_1_1_models_1_1_error_view_model" ],
        [ "Feedback", "class_f_a_q_chat_bot_1_1_models_1_1_feedback.html", "class_f_a_q_chat_bot_1_1_models_1_1_feedback" ],
        [ "OpcoesChatBot", "class_f_a_q_chat_bot_1_1_models_1_1_opcoes_chat_bot.html", "class_f_a_q_chat_bot_1_1_models_1_1_opcoes_chat_bot" ],
        [ "Pergunta", "class_f_a_q_chat_bot_1_1_models_1_1_pergunta.html", "class_f_a_q_chat_bot_1_1_models_1_1_pergunta" ]
      ] ],
      [ "Services", "namespace_f_a_q_chat_bot_1_1_services.html", [
        [ "GeminiChatService", "class_f_a_q_chat_bot_1_1_services_1_1_gemini_chat_service.html", "class_f_a_q_chat_bot_1_1_services_1_1_gemini_chat_service" ],
        [ "IChatService", "interface_f_a_q_chat_bot_1_1_services_1_1_i_chat_service.html", "interface_f_a_q_chat_bot_1_1_services_1_1_i_chat_service" ]
      ] ]
    ] ],
    [ "$", "class_0b.html", "class_0b" ],
    [ "Alert", "class_alert.html", "class_alert" ],
    [ "Backdrop", "class_backdrop.html", "class_backdrop" ],
    [ "BaseComponent", "class_base_component.html", "class_base_component" ],
    [ "Bt", "class_bt.html", "class_bt" ],
    [ "bt", "classbt.html", "classbt" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Carousel", "class_carousel.html", "class_carousel" ],
    [ "Collapse", "class_collapse.html", "class_collapse" ],
    [ "Dropdown", "class_dropdown.html", "class_dropdown" ],
    [ "et", "classet.html", "classet" ],
    [ "FocusTrap", "class_focus_trap.html", "class_focus_trap" ],
    [ "ft", "classft.html", "classft" ],
    [ "H", "class_h.html", "class_h" ],
    [ "He", "class_he.html", "class_he" ],
    [ "HomeController", "class_home_controller.html", "class_home_controller" ],
    [ "ii", "classii.html", "classii" ],
    [ "Kt", "class_kt.html", "class_kt" ],
    [ "Le", "class_le.html", "class_le" ],
    [ "Lt", "class_lt.html", "class_lt" ],
    [ "Modal", "class_modal.html", "class_modal" ],
    [ "ni", "classni.html", "classni" ],
    [ "nt", "classnt.html", "classnt" ],
    [ "Oe", "class_oe.html", "class_oe" ],
    [ "Offcanvas", "class_offcanvas.html", "class_offcanvas" ],
    [ "Pe", "class_pe.html", "class_pe" ],
    [ "Popover", "class_popover.html", "class_popover" ],
    [ "pt", "classpt.html", "classpt" ],
    [ "Qt", "class_qt.html", "class_qt" ],
    [ "R", "class_r.html", "class_r" ],
    [ "ri", "classri.html", "classri" ],
    [ "ScrollBarHelper", "class_scroll_bar_helper.html", "class_scroll_bar_helper" ],
    [ "ScrollSpy", "class_scroll_spy.html", "class_scroll_spy" ],
    [ "Se", "class_se.html", "class_se" ],
    [ "Tab", "class_tab.html", "class_tab" ],
    [ "Te", "class_te.html", "class_te" ],
    [ "Toast", "class_toast.html", "class_toast" ],
    [ "Tooltip", "class_tooltip.html", "class_tooltip" ],
    [ "Tt", "class_tt.html", "class_tt" ],
    [ "Vt", "class_vt.html", "class_vt" ],
    [ "W", "class_w.html", "class_w" ],
    [ "Wt", "class_wt.html", "class_wt" ],
    [ "wt", "classwt.html", "classwt" ],
    [ "Xe", "class_xe.html", "class_xe" ],
    [ "Z", "class_z.html", "class_z" ],
    [ "Ze", "class_ze.html", "class_ze" ]
];